### ISSUE TITLE
installation fails on R 4.2.2 on Linux/i386, installed via conda. 

### ISSUE THREAD

**Issue by ctb** [Arcadia-Science/sourmashconsumr#75]
with R installed via the following conda environment spec,
```
name: env
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.8
    - snakemake-minimal>=7.19.1,<8
    - sourmash>=4.6,<5
    - curl
    - r-ggplot2
    - r-pheatmap
    - r-viridis
    - r-ggplotify
    - r-rmarkdown
```
result in the set of installed packages (`mamba list` output attached), running the `remotes::install` command in the README results in:
[mamba-list.txt](https://github.com/Arcadia-Science/sourmashconsumr/files/10991333/mamba-list.txt)

```
...
* checking for file ‘/tmp/Rtmp32aOFf/remotes716552f5280e/Arcadia-Science-sourmashconsumr-9ceaa18/DESCRIPTION’ ... OK
* preparing ‘sourmashconsumr’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘sourmashconsumr_0.1.0.tar.gz’
ERROR: dependencies ‘httr’, ‘metacoder’, ‘phyloseq’ are not available for package ‘sourmashconsumr’
```

Not sure there's anything you can do about this, but wanted to document it here ;).

**Comment by taylorreiter** [comment]
thank you very much, this is super helpful. There are some things I can do. I'm disappointed in `httr` being missing, but for both metacoder and phyloseq I can move them to "suggests" instead of dependencies and then print a message that provides how to install them. That's the long term solution at least. Even better -- i need to make this a CRAN package and then build a conda-forge package for it...it's on my to list!

in the mean time, if you would still like to try and get it to install, could you try:
```
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Arcadia-Science/sourmashconsumr")
```

if that works, I'll add it to the docs as an alternative way of installing for now. (biocmanager does a better job of dependency management than `install.packages()`)

**Comment by taylorreiter** [comment]
phyloseq is also in conda -- `bioconductor-phyloseq`. the `devenv.yml` on the main branch has all of the dependencies that should allow facile installation https://github.com/Arcadia-Science/sourmashconsumr/blob/main/devenv.yml

**Comment by ctb** [comment]
> phyloseq is also in conda -- `bioconductor-phyloseq`. the `devenv.yml` on the main branch has all of the dependencies that should allow facile installation https://github.com/Arcadia-Science/sourmashconsumr/blob/main/devenv.yml, although R does annoying things on install when cran bumps versions so still might be sticky

I should have guessed & looked for these files 😆 

I'll investigate and report back when I get a chance!

**Comment by ctb** [comment]
update: got it to work! Had to fix a typo in `devenv.yml`. Ref  https://github.com/Arcadia-Science/sourmashconsumr/pull/76.
